# wallust v3.4
#
# You can copy this file to ~/.config/wallust/wallust.toml (keep in mind is a sample config)

# SIMPLE TUTORIAL, or `man wallust.5`:
# https://explosion-mental.codeberg.page/wallust/
#
# If comming from v2: https://explosion-mental.codeberg.page/wallust/v3.html#wallusttoml

# Global section - values below can be overwritten by command line flags

# How the image is parse, in order to get the colors:
# full - resized - wal - thumb -  fastresize - kmeans
backend = "fastresize"

# What color space to use to produce and select the most prominent colors:
# lab - labmixed - lch - lchmixed
color_space = "lch"

# Use the most prominent colors in a way that makes sense, a scheme color palette:
# dark - dark16 - darkcomp - darkcomp16
# light - light16 - lightcomp - lightcomp16
# harddark - harddark16 - harddarkcomp - harddarkcomp16
# softdark - softdark16 - softdarkcomp - softdarkcomp16
# softlight - softlight16 - softlightcomp - softlightcomp16
palette = "dark16"

# Ensures a "readable contrast" (OPTIONAL, disabled by default)
# Should only be enabled when you notice an unreadable contrast frequently happening
# with your images. The reference color for the contrast is the background color.
check_contrast = true

# Color saturation, between [1% and 100%] (OPTIONAL, disabled by default)
# usually something higher than 50 increases the saturation and below
# decreases it (on a scheme with strong and vivid colors)
#saturation = 35

# Alpha value for templating, by default 100 (no other use whatsoever)
#alpha = 100

[apply]
term = false
sequences = false

[templates]

# NOTE: prefer '' over "" for paths, avoids escaping.
# template: A RELATIVE path that points to `~/.config/wallust/template` (depends on platform)
# target: ABSOLUTE path in which to place a file with generated templated values.
# ยก If either one is a directory, then both SHOULD be one. !

# Hyprland
colors-hyprland = { template = 'colors-hyprland', target = '~/.config/hypr/colors-hyprland' }

#Hyprpaper
hyprpaper = { template = 'hyprpaper.conf', target = '~/.config/hypr/hyprpaper.conf' }

# Hyprlock
colors-hyprlock = { template = 'colors-hyprlock', target = '~/.config/hypr/colors-hyprlock' }

# Kitty terminal
colors-kitty = { template = 'colors-kitty.conf', target = '~/.config/kitty/colors-kitty.conf' }

# Dmenu
dmenu = { template = 'dmenu.Xresources', target = '~/.Xresources.d/dmenu.Xresources' }

# Rofi
rofi-colors = { template = 'rofi-colors.rasi', target = '~/.config/rofi/rofi-colors.rasi' }
rofi-launcher = { template = 'rofi-launcher-config.rasi', target = '~/.config/rofi/rofi-launcher-config.rasi' }
rofi-powermenu = { template = 'rofi-powermenu-config.rasi', target = '~/.config/rofi/rofi-powermenu-config.rasi' }
rofi-wallpaper-sel = { template = 'rofi-wallpaper-sel.rasi', target = '~/.config/rofi/rofi-wallpaper-sel.rasi' }
rofi-simple = { template = 'rofi-simple-config.rasi', target = '~/.config/rofi/rofi-simple-config.rasi' }

wezterm_colours = {template = 'wezterm_colours.lua', target = '~/.config/wezterm/wezterm_colours.lua'}
waybar-colours = {template = 'waybar-colours.css', target = '~/.config/waybar/waybar-colours.css'}
mako-config = {template = 'mako-config', target = '~/.config/mako/config'}

archlinux-icon = {template = 'archlinux-icon.svg', target = '~/.config/waybar/archlinux-icon.svg'}
